reformat file

diff --git a/.github/workflows/yt-dlp.yml b/.github/workflows/yt-dlp.yml
--- a/.github/workflows/yt-dlp.yml
+++ b/.github/workflows/yt-dlp.yml
@@ -1,64 +1,54 @@
 name: YT-DLP Download
-
 on:
-    workflow_dispatch:
-        inputs:
-            dl_url:
-                description: 'URL to download'
-                required: true
-                type: string
-            output:
-                description: 'Output filename'
-                required: true
-                type: string
-
+  workflow_dispatch:
+    inputs:
+      dl_url:
+        description: 'URL to download'
+        required: true
+        type: string
+      output:
+        description: 'Output filename'
+        required: true
+        type: string
 jobs:
-    download:
-        runs-on: ubuntu-latest
-
-        steps:
-            - name: Checkout repository
-              uses: actions/checkout@v4
-
-            - name: Setup yt-dlp
-              uses: AnimMouse/setup-yt-dlp@v3
-
-            - name: Setup yt-dlp YouTube cookies
-              uses: AnimMouse/setup-yt-dlp/cookies@v3
-              with:
-                cookies: ${{ secrets.YT_COOKIES }}
-
-            - name: Get filename
-              run: |
-                    filename=$(yt-dlp --print filename -o "${{ inputs.output }}.%(ext)s" ${{ inputs.dl_url }})
-                    echo "Filename: $filename"
-                    if [ -z "$filename" ]; then
-                        echo "Error: Filename could not be determined."
-                        exit 1
-                    fi
-                    echo "output=$filename" >> $GITHUB_ENV
-
-            - name: Download video
-              run: |
-                    yt-dlp ${{ inputs.dl_url }} -o "${{ inputs.output }}.%(ext)s"
-
-            - name: Update yt-dlp YouTube cookies
-              uses: AnimMouse/setup-yt-dlp/cookies/update@v3
-              with:
-                cookies_secret_name: YT_COOKIES
-                token: ${{ secrets.SECRET_ACCESS_TOKEN }}
-
-            - name: List downloaded files
-              run: |
-                    echo "Downloaded files:"
-                    ls -lh
-                    echo "Download complete!"
-
-            - name: Upload to gdrive
-              uses: adityak74/google-drive-upload-git-action@main
-              with:
-                credentials: ${{ secrets.GSA_CRED }}
-                filename: ${{ env.output }}
-                folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
-                name: ${{ env.output }}
-                overwrite: "true"
+  download:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Setup yt-dlp
+        uses: AnimMouse/setup-yt-dlp@v3
+      - name: Setup yt-dlp YouTube cookies
+        uses: AnimMouse/setup-yt-dlp/cookies@v3
+        with:
+          cookies: ${{ secrets.YT_COOKIES }}
+      - name: Get filename
+        run: |
+          filename=$(yt-dlp --print filename -o "${{ inputs.output }}.%(ext)s" ${{ inputs.dl_url }})
+          echo "Filename: $filename"
+          if [ -z "$filename" ]; then
+            echo "Error: Filename could not be determined."
+            exit 1
+          fi
+          echo "output=$filename" >> $GITHUB_ENV
+      - name: Download video
+        run: |
+          yt-dlp ${{ inputs.dl_url }} -o "${{ inputs.output }}.%(ext)s"
+      - name: Update yt-dlp YouTube cookies
+        uses: AnimMouse/setup-yt-dlp/cookies/update@v3
+        with:
+          cookies_secret_name: YT_COOKIES
+          token: ${{ secrets.SECRET_ACCESS_TOKEN }}
+      - name: List downloaded files
+        run: |
+          echo "Downloaded files:"
+          ls -lh
+          echo "Download complete!"
+      - name: Upload to gdrive
+        uses: adityak74/google-drive-upload-git-action@main
+        with:
+          credentials: ${{ secrets.GSA_CRED }}
+          filename: ${{ env.output }}
+          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
+          name: ${{ env.output }}
+          overwrite: "true"
